/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2so;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author victoriadepalma
 */
public class Interfaz extends javax.swing.JFrame {
    
  
   
    
    public static String[] namesZ=new String[10];
    public static String[] namesST=new String[10];
    public  int[] listaGanadores= new int[150];
    public Personaje[] personajesZ= new Personaje[30];
    public Personaje[] personajesST = new Personaje[30];
    
    int contadorIdZ=0;
    int contadorIdSF=0;
    
  
    
    Cola cola1Z = new Cola();
    Cola cola2Z = new Cola();
    Cola cola3Z = new Cola();
    Cola cola1SF = new Cola();
    Cola cola2SF = new Cola();
    Cola cola3SF = new Cola();
    Cola colaRZ = new Cola();
    Cola colaRSF = new Cola();
    
    
        Admin admin = new Admin(this);
        Inteligencia inteligencia = new Inteligencia(this, this.cola1Z, this.cola2Z, this.cola3Z, this.cola1SF, this.cola2SF, this.cola3SF, this.colaRZ, this.colaRSF, admin);
   
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        namesZ[0]="Link";
        namesZ[1]="Princesa Zelda";
        namesZ[2]="Ganondorf";
        namesZ[3]="Impa";
        namesZ[4]="Darunia";
        namesZ[5]="Tingle";
        namesZ[6]="Navi";
        namesZ[7]="Sheik";
        namesZ[8]="Epona";
        namesZ[9]="Rauru";
        
        namesST[0]="Ryu";
        namesST[1]="M.Bison";
        namesST[2]="Zangief";
        namesST[3]="Akuma";
        namesST[4]="Guile";
        namesST[5]="Gouken";
        namesST[6]="Chun-Li";
        namesST[7]="Menat";
        namesST[8]="Juni";
        namesST[9]="Blanka";
    
        
    }
     
    
    public void inicializarPersonaje(){
        for (int i=0;i< personajesZ.length;i++){
            Random randomGenerator= new Random();
            int idRandom=randomGenerator.nextInt(10);
            
            personajesZ[i] = new Personaje(contadorIdZ, namesZ[idRandom], null,0,0); //lista de objetos personajes Zelda
            
            this.contadorIdZ++;
            System.out.println("se hizo bien");
 
        }
          for (int i=0;i<personajesST.length;i++){
              Random randomGenerator= new Random();
            int idRandom=randomGenerator.nextInt(10);

            personajesST[i]=new Personaje(contadorIdSF, namesST[idRandom], null,0,0); //lista de objetos personajes Street Fighter
            this.contadorIdSF++;
            
           
        }

    }
    
    public void visualizarColas(){
           String cola1z = cola1Z.imprimirColaZelda();
           String cola1sf = cola1SF.imprimirColaSF();
           String cola2z = cola2Z.imprimirColaZelda();
           String cola2sf = cola2SF.imprimirColaSF();
           String cola3z = cola3Z.imprimirColaZelda();
           String cola3sf = cola3SF.imprimirColaSF();
           String colarz = colaRZ.imprimirColaZelda();
           String colarsf = colaRSF.imprimirColaSF();
           
           txtNivel1Z.setText(cola1z);
           txtNivel2Z.setText(cola2z);
           txtNivel3Z.setText(cola3z);
           txtRZ.setText(colarz);
           txtNivel1SF.setText(cola1sf);
           txtNivel2SF.setText(cola2sf);
           txtNivel3SF.setText(cola3sf);
           txtRSF.setText(colarsf);
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdZ = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreZelda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCombatesGanadosZelda = new javax.swing.JTextField();
        txtCombatesGanadosSF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdSF = new javax.swing.JTextField();
        txtNombreSF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel24 = new javax.swing.JLabel();
        txtEstadoIA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRSF = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNivel1Z = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNivel2Z = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNivel3Z = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtRZ = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtNivel1SF = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtNivel2SF = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtNivel3SF = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 160));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 150, 160));

        jLabel1.setText("Nivel 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jLabel2.setText("Nivel 2 ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jLabel3.setText("Nivel 3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        jLabel4.setText("Nivel 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel5.setText("Nivel 2 ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel6.setText("Nivel 3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel8.setText("Resfuerzo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel9.setText("Resfuerzo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel10.setText("id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtIdZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdZActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

        jLabel11.setText("Nombre");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtNombreZelda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreZeldaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreZelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 60, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel13.setText("ZELDA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel14.setText("Resultado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, 20));
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 150, 30));

        jLabel15.setText("STREET FIGHTER");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        jLabel16.setText("V.S.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel17.setText("Control de Tiempo");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel18.setText("Combates ganados: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jLabel19.setText("Combates ganados: ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txtCombatesGanadosZelda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombatesGanadosZeldaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCombatesGanadosZelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, 30));
        jPanel1.add(txtCombatesGanadosSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 80, 30));

        jLabel20.setText("Habilidades ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel21.setText("id");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel22.setText("Nombre");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        txtIdSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSFActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 70, 30));
        jPanel1.add(txtNombreSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 70, -1));

        jLabel23.setText("Habilidades ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 70, -1));
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 80, 20));

        jLabel24.setText("Estado Inteligencia Artificial");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        txtEstadoIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoIAActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstadoIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, 30));

        jButton1.setText("cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        txtRSF.setColumns(20);
        txtRSF.setRows(5);
        jScrollPane1.setViewportView(txtRSF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 370, 40));

        txtNivel1Z.setColumns(20);
        txtNivel1Z.setRows(5);
        jScrollPane2.setViewportView(txtNivel1Z);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 380, 40));

        txtNivel2Z.setColumns(20);
        txtNivel2Z.setRows(5);
        jScrollPane3.setViewportView(txtNivel2Z);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 380, 40));

        txtNivel3Z.setColumns(20);
        txtNivel3Z.setRows(5);
        jScrollPane4.setViewportView(txtNivel3Z);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 380, 40));

        txtRZ.setColumns(20);
        txtRZ.setRows(5);
        jScrollPane5.setViewportView(txtRZ);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 380, 40));

        txtNivel1SF.setColumns(20);
        txtNivel1SF.setRows(5);
        jScrollPane6.setViewportView(txtNivel1SF);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 370, 40));

        txtNivel2SF.setColumns(20);
        txtNivel2SF.setRows(5);
        jScrollPane7.setViewportView(txtNivel2SF);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 370, 40));

        txtNivel3SF.setColumns(20);
        txtNivel3SF.setRows(5);
        jScrollPane8.setViewportView(txtNivel3SF);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 370, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreZeldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreZeldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreZeldaActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
         this.inicializarPersonaje();
        this.visualizarColas();
 
        this.txtTiempo.setText(Integer.toString(5));
        this.txtEstadoIA.setText("Esperando");
        admin.asignarColasNiveles(this.cola1Z, this.cola2Z, this.cola3Z, this.cola1SF, this.cola2SF, this.cola3SF);
        inteligencia.start();
        
//       
        
    }//GEN-LAST:event_IniciarActionPerformed

    private void txtCombatesGanadosZeldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombatesGanadosZeldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombatesGanadosZeldaActionPerformed

    private void txtIdSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSFActionPerformed

    private void txtEstadoIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoIAActionPerformed

    private void txtIdZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdZActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSlider jSlider1;
    public static javax.swing.JTextField txtCombatesGanadosSF;
    public static javax.swing.JTextField txtCombatesGanadosZelda;
    public static javax.swing.JTextField txtEstadoIA;
    public javax.swing.JTextField txtIdSF;
    public javax.swing.JTextField txtIdZ;
    private javax.swing.JTextArea txtNivel1SF;
    private javax.swing.JTextArea txtNivel1Z;
    private javax.swing.JTextArea txtNivel2SF;
    private javax.swing.JTextArea txtNivel2Z;
    private javax.swing.JTextArea txtNivel3SF;
    private javax.swing.JTextArea txtNivel3Z;
    public javax.swing.JTextField txtNombreSF;
    public javax.swing.JTextField txtNombreZelda;
    private javax.swing.JTextArea txtRSF;
    private javax.swing.JTextArea txtRZ;
    public static javax.swing.JTextField txtResultado;
    public javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
